### ISSUE TITLE
Add a version string to libraries?

### ISSUE THREAD

**Issue by ghost** [bstatcomp/RandomCL#4]
First of all, thank you for writing this library! I'm using it in a raytracing code, it is much faster than the previous RNG implementation I was using.

I am referencing the lib and its license in my code, but I am missing a version number. Could you please add a version string (e.g., via #define RANDOMCL_VERSION_STR "1.0.0") to the library?

**Comment by t4c1** [comment]
@Mscholli Do you just need to have version of the library specified somewhere so you can reference it? Or do you for some reason explicitely require version string in code?

**Comment by ghost** [comment]
@t4c1 Yes, I just need a version number to reference. 
A version string in code that can be inserted automatically during compilation would be even nicer, so that I don't need to remember updating the version in the future. But that's more a 'desirement' than a requirement.

**Comment by t4c1** [comment]
I decided to add a separate header with version string the way you suggested.
